version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Ajuste a memória conforme necessário
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.5
    container_name: filebeat
    user: root # Necessário para acessar os logs do Docker
    volumes:
      # Monta o arquivo de configuração (agora como read-write, o padrão)
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      # Monta o socket do Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    # --- ESTA É A CORREÇÃO ---
    # Este comando corrige as permissões do .yml DENTRO do container
    # antes de iniciar o Filebeat.
    command: >
      sh -c "
        chmod go-w /usr/share/filebeat/filebeat.yml &&
        filebeat -e -c /usr/share/filebeat/filebeat.yml
      "
    # ---------------------------

    depends_on:
      - elasticsearch
    networks:
      - elk

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch_data:

